# Generated by Django 5.1 on 2024-09-06 05:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_created_at_listing_winner_user_watchlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=django.utils.timezone.now, max_digits=12),
            preserve_default=False,
        ),
    ]
